#!/usr/bin/env python3
"""
☁️ Cloud-Agent
Cloud Engineer агент

Создаёт:
- Terraform конфигурации
- Kubernetes манифесты
- CloudFormation/CDK
- CI/CD pipelines
"""

import argparse
from pathlib import Path
from typing import Dict


class CloudAgent:
    """
    ☁️ Cloud-Agent
    
    Специализация: Cloud Infrastructure
    Платформы: AWS, GCP, Azure, Kubernetes
    """
    
    NAME = "☁️ Cloud-Agent"
    ROLE = "Cloud Engineer"
    EXPERTISE = ["AWS", "GCP", "Kubernetes", "Terraform", "CI/CD"]
    
    def process_request(self, request: str, platform: str = "aws") -> Dict[str, str]:
        files = {}
        
        request_lower = request.lower()
        
        if "terraform" in request_lower or "infrastructure" in request_lower:
            files = self._generate_terraform(platform)
        elif "kubernetes" in request_lower or "k8s" in request_lower:
            files = self._generate_kubernetes()
        elif "github actions" in request_lower or "ci/cd" in request_lower:
            files = self._generate_cicd()
        elif "docker" in request_lower:
            files = self._generate_docker()
        else:
            files = self._generate_terraform(platform)
        
        return files
    
    def _generate_terraform(self, platform: str) -> Dict[str, str]:
        files = {}
        
        files["main.tf"] = f"""# ☁️ Terraform Configuration
# Provider: {platform.upper()}
# Generated by Cloud-Agent

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    {platform} = {{
      source  = "hashicorp/{platform}"
      version = "~> 5.0"
    }}
  }}
  backend "s3" {{
    bucket = "terraform-state"
    key    = "infrastructure/terraform.tfstate"
    region = "us-east-1"
  }}
}}

provider "{platform}" {{
  region = var.region
}}

# VPC
module "vpc" {{
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.0"

  name = "${{var.project_name}}-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["${{var.region}}a", "${{var.region}}b", "${{var.region}}c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = false

  tags = {{
    Project     = var.project_name
    Environment = var.environment
  }}
}}

# EKS Cluster
module "eks" {{
  source  = "terraform-aws-modules/eks/aws"
  version = "19.0"

  cluster_name    = "${{var.project_name}}-cluster"
  cluster_version = "1.28"

  vpc_id                         = module.vpc.vpc_id
  subnet_ids                     = module.vpc.private_subnets
  cluster_endpoint_public_access = true

  eks_managed_node_groups = {{
    general = {{
      desired_size = 2
      min_size     = 1
      max_size     = 10

      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
    }}
  }}
}}

# RDS Database
module "rds" {{
  source  = "terraform-aws-modules/rds/aws"
  version = "6.0"

  identifier = "${{var.project_name}}-db"

  engine            = "postgres"
  engine_version    = "15"
  instance_class    = "db.t3.micro"
  allocated_storage = 20

  db_name  = var.db_name
  username = var.db_username
  password = var.db_password
  port     = "5432"

  vpc_security_group_ids = [module.vpc.default_security_group_id]
  db_subnet_group_name   = module.vpc.database_subnet_group

  backup_retention_period = 7
  backup_window          = "03:00-04:00"
}}
"""
        
        files["variables.tf"] = """variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name"
  type        = string
}

variable "environment" {
  description = "Environment"
  type        = string
  default     = "production"
}

variable "db_name" {
  description = "Database name"
  type        = string
}

variable "db_username" {
  description = "Database username"
  type        = string
}

variable "db_password" {
  description = "Database password"
  type        = string
  sensitive   = true
}
"""
        
        return files
    
    def _generate_kubernetes(self) -> Dict[str, str]:
        files = {}
        
        files["deployment.yaml"] = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
"""
        
        return files
    
    def _generate_cicd(self) -> Dict[str, str]:
        files = {}
        
        files["github-actions.yml"] = """name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run linting
        run: npm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t app:${{ github.sha }} .
      
      - name: Push to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app-deployment web=app:${{ github.sha }}
          kubectl rollout status deployment/app-deployment
"""
        
        return files
    
    def _generate_docker(self) -> Dict[str, str]:
        files = {}
        
        files["Dockerfile"] = """# Multi-stage build
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json .

USER node

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]
"""
        
        files["docker-compose.yml"] = """version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:pass@db:5432/dbname
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
"""
        
        return files


def main():
    parser = argparse.ArgumentParser(description="☁️ Cloud-Agent — Cloud Engineer")
    parser.add_argument("request", nargs="?", help="Что настроить")
    parser.add_argument("--platform", "-p", default="aws", choices=["aws", "gcp", "azure"])
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = CloudAgent()
    
    if args.request:
        print(f"☁️ {agent.NAME} настраивает: {args.request}")
        files = agent.process_request(args.request, args.platform)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"☁️ {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
