#!/usr/bin/env python3
"""
🗄️ Database-Agent
Database Engineer агент

Создаёт:
- SQL схемы
- Миграции
- Индексы
- Оптимизацию запросов
"""

import argparse
from pathlib import Path
from typing import Dict


class DatabaseAgent:
    """
    🗄️ Database-Agent
    
    Специализация: Database Engineering
    Экспертиза: PostgreSQL, MySQL, MongoDB, Redis
    """
    
    NAME = "🗄️ Database-Agent"
    ROLE = "Database Engineer"
    EXPERTISE = ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Query Optimization", "Indexing"]
    
    def process_request(self, request: str, db_type: str = "postgres") -> Dict[str, str]:
        files = {}
        
        request_lower = request.lower()
        
        if "schema" in request_lower or "схема" in request_lower:
            files = self._generate_schema(request, db_type)
        elif "migration" in request_lower or "миграция" in request_lower:
            files = self._generate_migrations(request, db_type)
        elif "seed" in request_lower or "данные" in request_lower:
            files = self._generate_seed_data(request, db_type)
        elif "index" in request_lower or "индекс" in request_lower:
            files = self._generate_indexes(request, db_type)
        else:
            files = self._generate_schema(request, db_type)
        
        return files
    
    def _generate_schema(self, feature: str, db_type: str) -> Dict[str, str]:
        files = {}
        
        files["schema.sql"] = f"""-- 🗄️ Database Schema
-- Generated by Database-Agent
-- Feature: {feature}

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    role VARCHAR(50) DEFAULT 'user',
    is_active BOOLEAN DEFAULT true,
    email_verified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sessions table
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(512) NOT NULL,
    ip_address INET,
    user_agent TEXT,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Projects table
CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id UUID REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'active',
    settings JSONB DEFAULT '{{}}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tasks table
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'todo',
    priority VARCHAR(20) DEFAULT 'medium',
    assignee_id UUID REFERENCES users(id) ON DELETE SET NULL,
    due_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comments table
CREATE TABLE comments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit log
CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    table_name VARCHAR(100) NOT NULL,
    record_id UUID NOT NULL,
    action VARCHAR(20) NOT NULL,
    old_data JSONB,
    new_data JSONB,
    user_id UUID REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_token ON sessions(token);
CREATE INDEX idx_projects_owner_id ON projects(owner_id);
CREATE INDEX idx_tasks_project_id ON tasks(project_id);
CREATE INDEX idx_tasks_assignee_id ON tasks(assignee_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_comments_task_id ON comments(task_id);
CREATE INDEX idx_audit_log_table_name ON audit_log(table_name);
CREATE INDEX idx_audit_log_record_id ON audit_log(record_id);

-- Triggers for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_comments_updated_at BEFORE UPDATE ON comments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
"""
        
        files["erd.md"] = f"""# 📊 Entity Relationship Diagram

```mermaid
erDiagram
    USERS ||--o{{ SESSIONS : has
    USERS ||--o{{ PROJECTS : owns
    USERS ||--o{{ TASKS : assigned_to
    PROJECTS ||--o{{ TASKS : contains
    TASKS ||--o{{ COMMENTS : has
    
    USERS {{
        uuid id PK
        string email
        string password_hash
        string first_name
        string last_name
        string role
        boolean is_active
        timestamp created_at
    }}
    
    SESSIONS {{
        uuid id PK
        uuid user_id FK
        string token
        inet ip_address
        text user_agent
        timestamp expires_at
    }}
    
    PROJECTS {{
        uuid id PK
        string name
        text description
        uuid owner_id FK
        string status
        jsonb settings
        timestamp created_at
    }}
    
    TASKS {{
        uuid id PK
        uuid project_id FK
        string title
        text description
        string status
        string priority
        uuid assignee_id FK
        timestamp due_date
        timestamp created_at
    }}
    
    COMMENTS {{
        uuid id PK
        uuid task_id FK
        uuid user_id FK
        text content
        timestamp created_at
    }}
```
"""
        
        return files
    
    def _generate_migrations(self, feature: str, db_type: str) -> Dict[str, str]:
        files = {}
        
        files["001_initial.sql"] = f"""-- Migration: Initial schema
-- Created: Database-Agent

-- Up
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Down
-- DROP TABLE IF EXISTS users;
"""
        
        files["002_add_profile.sql"] = """-- Migration: Add profile fields

-- Up
ALTER TABLE users 
    ADD COLUMN first_name VARCHAR(100),
    ADD COLUMN last_name VARCHAR(100),
    ADD COLUMN avatar_url VARCHAR(500);

-- Down
-- ALTER TABLE users DROP COLUMN first_name, DROP COLUMN last_name, DROP COLUMN avatar_url;
"""
        
        return files
    
    def _generate_seed_data(self, feature: str, db_type: str) -> Dict[str, str]:
        files = {}
        
        files["seed.sql"] = f"""-- 🌱 Seed Data
-- Generated by Database-Agent

-- Admin user
INSERT INTO users (email, password_hash, first_name, last_name, role)
VALUES (
    'admin@example.com',
    '$2b$12$...', -- hashed password
    'Admin',
    'User',
    'admin'
);

-- Sample projects
INSERT INTO projects (name, description, owner_id, status)
VALUES 
    ('Project Alpha', 'First project', (SELECT id FROM users WHERE email = 'admin@example.com'), 'active'),
    ('Project Beta', 'Second project', (SELECT id FROM users WHERE email = 'admin@example.com'), 'active');

-- Sample tasks
INSERT INTO tasks (project_id, title, description, status, priority)
SELECT 
    p.id,
    'Setup ' || p.name,
    'Initial setup for ' || p.name,
    'todo',
    'high'
FROM projects p;
"""
        
        return files
    
    def _generate_indexes(self, feature: str, db_type: str) -> Dict[str, str]:
        files = {}
        
        files["indexes.sql"] = """-- 📈 Performance Indexes
-- Generated by Database-Agent

-- User lookups
CREATE INDEX CONCURRENTLY idx_users_email_active ON users(email) WHERE is_active = true;
CREATE INDEX CONCURRENTLY idx_users_created_desc ON users(created_at DESC);

-- Session cleanup
CREATE INDEX CONCURRENTLY idx_sessions_expires ON sessions(expires_at) WHERE expires_at < NOW();

-- Task queries
CREATE INDEX CONCURRENTLY idx_tasks_project_status ON tasks(project_id, status);
CREATE INDEX CONCURRENTLY idx_tasks_assignee_status ON tasks(assignee_id, status) WHERE assignee_id IS NOT NULL;
CREATE INDEX CONCURRENTLY idx_tasks_due_date ON tasks(due_date) WHERE due_date IS NOT NULL;

-- Full-text search
CREATE INDEX CONCURRENTLY idx_projects_name_trgm ON projects USING gin (name gin_trgm_ops);

-- JSONB queries
CREATE INDEX CONCURRENTLY idx_projects_settings_gin ON projects USING gin (settings);

-- Composite index for common query
CREATE INDEX CONCURRENTLY idx_tasks_common ON tasks(project_id, status, priority, created_at DESC);
"""
        
        return files


def main():
    parser = argparse.ArgumentParser(description="🗄️ Database-Agent — Database Engineer")
    parser.add_argument("request", nargs="?", help="Что спроектировать")
    parser.add_argument("--db", "-d", default="postgres", choices=["postgres", "mysql", "mongodb"])
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = DatabaseAgent()
    
    if args.request:
        print(f"🗄️ {agent.NAME} проектирует: {args.request}")
        files = agent.process_request(args.request, args.db)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"🗄️ {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
