#!/usr/bin/env python3
"""
📦 Dependency-Agent
Dependency Management Specialist

Управляет зависимостями проектов.
Обновления, аудит, оптимизация.
"""

import argparse
from pathlib import Path
from typing import Dict


class DependencyAgent:
    """
    📦 Dependency-Agent
    
    Специализация: Dependency Management
    Задачи: Обновление, аудит, оптимизация зависимостей
    """
    
    NAME = "📦 Dependency-Agent"
    ROLE = "Dependency Manager"
    EXPERTISE = ["Dependency Management", "Security Audit", "Updates", "Optimization"]
    
    def process_request(self, request: str) -> Dict[str, str]:
        files = {}
        
        files["dependency-update.yml"] = self._generate_github_action()
        files["renovate.json"] = self._generate_renovate_config()
        files["dependency-guide.md"] = self._generate_guide()
        files["update-script.sh"] = self._generate_update_script()
        
        return files
    
    def _generate_github_action(self) -> str:
        return """name: Dependency Update

on:
  schedule:
    # Run every Monday at 9:00 AM
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for updates
      run: |
        npm install -g npm-check-updates
        ncu -u
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
    
    - name: Run tests
      run: npm test
      continue-on-error: true
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '⬆️ Update dependencies'
        body: |
          ## Automated Dependency Update
          
          This PR updates project dependencies to their latest versions.
          
          ### Changes
          - Updated packages to latest compatible versions
          - Ran security audit
          
          ### Checklist
          - [ ] Review breaking changes
          - [ ] Run manual tests
          - [ ] Check CI/CD pipeline
        branch: deps/update-dependencies
        delete-branch: true
"""
    
    def _generate_renovate_config(self) -> str:
        return """{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended",
    ":semanticCommits",
    ":semanticCommitTypeAll(chore)",
    ":dependencyDashboard"
  ],
  "timezone": "Europe/Moscow",
  "schedule": [
    "before 9am on Monday"
  ],
  "packageRules": [
    {
      "groupName": "devDependencies",
      "matchDepTypes": ["devDependencies"],
      "automerge": true,
      "automergeType": "pr",
      "platformAutomerge": true
    },
    {
      "groupName": "React packages",
      "matchPackageNames": ["react", "react-dom", "@types/react", "@types/react-dom"],
      "matchPackagePatterns": ["^@react/"]
    },
    {
      "groupName": "TypeScript",
      "matchPackageNames": ["typescript", "@types/*"]
    },
    {
      "groupName": "Testing packages",
      "matchPackageNames": ["vitest", "jest", "cypress", "playwright"],
      "matchPackagePatterns": ["^@testing-library/"]
    },
    {
      "matchUpdateTypes": ["major"],
      "labels": ["dependencies", "major"],
      "reviewers": ["team:frontend"]
    },
    {
      "matchUpdateTypes": ["minor", "patch"],
      "labels": ["dependencies"],
      "automerge": true
    }
  ],
  "vulnerabilityAlerts": {
    "enabled": true,
    "schedule": ["at any time"]
  },
  "osvVulnerabilityAlerts": true
}
"""
    
    def _generate_update_script(self) -> str:
        return """#!/bin/bash
# Dependency Update Script
# Generated by Dependency-Agent

set -e

echo "🔄 Starting dependency update..."

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Update Node.js dependencies
update_node() {
    if [ -f "package.json" ]; then
        echo -e "${YELLOW}📦 Updating Node.js dependencies...${NC}"
        
        # Check outdated packages
        echo "📋 Checking outdated packages..."
        npm outdated || true
        
        # Install npm-check-updates if not present
        if ! command_exists ncu; then
            npm install -g npm-check-updates
        fi
        
        # Interactive update
        echo "🔄 Running npm-check-updates..."
        ncu -i
        
        # Install updated packages
        echo "📥 Installing updates..."
        npm install
        
        # Run audit
        echo "🔐 Running security audit..."
        npm audit fix || echo -e "${YELLOW}⚠️  Some vulnerabilities require manual review${NC}"
        
        # Run tests if available
        if npm run test --if-present 2>/dev/null; then
            echo -e "${GREEN}✅ Tests passed${NC}"
        else
            echo -e "${YELLOW}⚠️  No tests or tests failed${NC}"
        fi
        
        echo -e "${GREEN}✅ Node.js dependencies updated!${NC}"
    fi
}

# Update Python dependencies
update_python() {
    if [ -f "requirements.txt" ]; then
        echo -e "${YELLOW}🐍 Updating Python dependencies...${NC}"
        
        # Check outdated
        pip list --outdated
        
        # Install pip-audit if not present
        if ! command_exists pip-audit; then
            pip install pip-audit
        fi
        
        # Run security audit
        echo "🔐 Running security audit..."
        pip-audit || true
        
        echo -e "${GREEN}✅ Python dependencies checked!${NC}"
    fi
    
    if [ -f "pyproject.toml" ]; then
        echo -e "${YELLOW}🐍 Updating Poetry dependencies...${NC}"
        poetry update
        poetry audit || true
    fi
}

# Update Go dependencies
update_go() {
    if [ -f "go.mod" ]; then
        echo -e "${YELLOW}🐹 Updating Go dependencies...${NC}"
        go get -u ./...
        go mod tidy
        
        # Security check with Nancy
        if command_exists nancy; then
            go list -json -m all | nancy sleuth || true
        fi
        
        echo -e "${GREEN}✅ Go dependencies updated!${NC}"
    fi
}

# Update Rust dependencies
update_rust() {
    if [ -f "Cargo.toml" ]; then
        echo -e "${YELLOW}🦀 Updating Rust dependencies...${NC}"
        cargo update
        
        # Security audit
        if command_exists cargo-audit; then
            cargo audit || true
        fi
        
        echo -e "${GREEN}✅ Rust dependencies updated!${NC}"
    fi
}

# Main execution
echo "🔍 Detecting project type..."

update_node
update_python
update_go
update_rust

echo ""
echo -e "${GREEN}🎉 All dependencies updated!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review changes in package files"
echo "  2. Run tests: npm test / pytest / go test / cargo test"
echo "  3. Check application functionality"
echo "  4. Commit changes: git add -A && git commit -m 'chore: update dependencies'"
"""
    
    def _generate_guide(self) -> str:
        return """# Dependency Management Guide

## Best Practices

### 1. Pin Dependencies
```json
{
  "dependencies": {
    "package": "^1.2.3"  // Major version locked
  },
  "devDependencies": {
    "package": "~1.2.3"  // Patch only
  }
}
```

### 2. Lock Files
Always commit lock files to ensure reproducible builds:
- `package-lock.json` (npm)
- `yarn.lock` (yarn)
- `pnpm-lock.yaml` (pnpm)
- `poetry.lock` (Poetry)
- `Cargo.lock` (Rust)
- `go.sum` (Go)

### 3. Update Strategy

#### Minor/Patch Updates
- Auto-merge if tests pass
- Use Renovate or Dependabot

#### Major Updates
- Manual review required
- Check breaking changes
- Test thoroughly

### 4. Security

#### Regular Audits
```bash
# Node.js
npm audit
npm audit fix

# Python
pip-audit

# Go
nancy sleuth

# Rust
cargo audit
```

### 5. Dependency Dashboard

Use GitHub Dependency Graph to:
- Track dependencies
- Get security alerts
- Monitor licenses

## Tools

- **Renovate**: Automated dependency updates
- **Dependabot**: GitHub-native dependency updates
- **Snyk**: Security scanning
- **OWASP Dependency-Check**: Security auditing
"""


def main():
    parser = argparse.ArgumentParser(description="📦 Dependency-Agent — Dependencies")
    parser.add_argument("request", nargs="?", help="Задача")
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = DependencyAgent()
    
    if args.request:
        print(f"📦 {agent.NAME} создаёт: {args.request}")
        files = agent.process_request(args.request)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"📦 {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
