#!/usr/bin/env python3
"""
🎨 Figma-Agent
Design System агент

Создаёт:
- Design tokens
- Figma плагины
- Design system specs
"""

import argparse
from pathlib import Path
from typing import Dict


class FigmaAgent:
    """
    🎨 Figma-Agent
    
    Специализация: Design System
    Инструменты: Figma, Design Tokens, Style Dictionary
    """
    
    NAME = "🎨 Figma-Agent"
    ROLE = "Design System Specialist"
    EXPERTISE = ["Figma", "Design Tokens", "Style Dictionary", "Design Systems"]
    
    def process_request(self, request: str) -> Dict[str, str]:
        files = {}
        
        files["design_tokens.json"] = """{
  "color": {
    "primary": {
      "50": { "value": "#eff6ff", "type": "color" },
      "100": { "value": "#dbeafe", "type": "color" },
      "200": { "value": "#bfdbfe", "type": "color" },
      "300": { "value": "#93c5fd", "type": "color" },
      "400": { "value": "#60a5fa", "type": "color" },
      "500": { "value": "#3b82f6", "type": "color" },
      "600": { "value": "#2563eb", "type": "color" },
      "700": { "value": "#1d4ed8", "type": "color" },
      "800": { "value": "#1e40af", "type": "color" },
      "900": { "value": "#1e3a8a", "type": "color" }
    },
    "neutral": {
      "white": { "value": "#ffffff", "type": "color" },
      "50": { "value": "#fafafa", "type": "color" },
      "100": { "value": "#f5f5f5", "type": "color" },
      "200": { "value": "#e5e5e5", "type": "color" },
      "300": { "value": "#d4d4d4", "type": "color" },
      "400": { "value": "#a3a3a3", "type": "color" },
      "500": { "value": "#737373", "type": "color" },
      "600": { "value": "#525252", "type": "color" },
      "700": { "value": "#404040", "type": "color" },
      "800": { "value": "#262626", "type": "color" },
      "900": { "value": "#171717", "type": "color" }
    },
    "semantic": {
      "background": { "value": "{color.neutral.white}", "type": "color" },
      "text": { "value": "{color.neutral.900}", "type": "color" },
      "text-muted": { "value": "{color.neutral.500}", "type": "color" },
      "border": { "value": "{color.neutral.200}", "type": "color" }
    }
  },
  "font": {
    "family": {
      "sans": { "value": "Inter, system-ui, sans-serif", "type": "fontFamily" },
      "mono": { "value": "JetBrains Mono, monospace", "type": "fontFamily" }
    },
    "size": {
      "xs": { "value": "12px", "type": "fontSize" },
      "sm": { "value": "14px", "type": "fontSize" },
      "base": { "value": "16px", "type": "fontSize" },
      "lg": { "value": "18px", "type": "fontSize" },
      "xl": { "value": "20px", "type": "fontSize" },
      "2xl": { "value": "24px", "type": "fontSize" },
      "3xl": { "value": "30px", "type": "fontSize" },
      "4xl": { "value": "36px", "type": "fontSize" }
    },
    "weight": {
      "normal": { "value": "400", "type": "fontWeight" },
      "medium": { "value": "500", "type": "fontWeight" },
      "semibold": { "value": "600", "type": "fontWeight" },
      "bold": { "value": "700", "type": "fontWeight" }
    }
  },
  "spacing": {
    "0": { "value": "0", "type": "spacing" },
    "1": { "value": "4px", "type": "spacing" },
    "2": { "value": "8px", "type": "spacing" },
    "3": { "value": "12px", "type": "spacing" },
    "4": { "value": "16px", "type": "spacing" },
    "5": { "value": "20px", "type": "spacing" },
    "6": { "value": "24px", "type": "spacing" },
    "8": { "value": "32px", "type": "spacing" },
    "10": { "value": "40px", "type": "spacing" },
    "12": { "value": "48px", "type": "spacing" },
    "16": { "value": "64px", "type": "spacing" }
  },
  "border": {
    "radius": {
      "none": { "value": "0", "type": "borderRadius" },
      "sm": { "value": "4px", "type": "borderRadius" },
      "base": { "value": "8px", "type": "borderRadius" },
      "md": { "value": "12px", "type": "borderRadius" },
      "lg": { "value": "16px", "type": "borderRadius" },
      "xl": { "value": "24px", "type": "borderRadius" },
      "full": { "value": "9999px", "type": "borderRadius" }
    }
  },
  "shadow": {
    "sm": {
      "value": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      "type": "boxShadow"
    },
    "base": {
      "value": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
      "type": "boxShadow"
    },
    "md": {
      "value": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
      "type": "boxShadow"
    },
    "lg": {
      "value": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)",
      "type": "boxShadow"
    }
  }
}
"""
        
        files["figma_plugin.js"] = """// Figma Plugin - Generated by Figma-Agent

figma.showUI(__html__, { width: 400, height: 500 });

// Get current selection
const selection = figma.currentPage.selection;

figma.ui.onmessage = async (msg) => {
  if (msg.type === 'export-selection') {
    if (selection.length === 0) {
      figma.notify('Please select a layer first');
      return;
    }
    
    const node = selection[0];
    const bytes = await node.exportAsync({
      format: 'PNG',
      constraint: { type: 'SCALE', value: 2 }
    });
    
    figma.ui.postMessage({
      type: 'export-complete',
      bytes: bytes
    });
  }
  
  if (msg.type === 'create-component') {
    // Create a button component
    const button = figma.createFrame();
    button.name = 'Button';
    button.layoutMode = 'HORIZONTAL';
    button.primaryAxisAlignItems = 'CENTER';
    button.counterAxisAlignItems = 'CENTER';
    button.paddingLeft = 16;
    button.paddingRight = 16;
    button.paddingTop = 8;
    button.paddingBottom = 8;
    button.fills = [{ type: 'SOLID', color: { r: 0.23, g: 0.39, b: 0.96 } }];
    button.topLeftRadius = 8;
    button.topRightRadius = 8;
    button.bottomLeftRadius = 8;
    button.bottomRightRadius = 8;
    
    const text = figma.createText();
    text.characters = 'Button';
    text.fontSize = 14;
    text.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
    
    button.appendChild(text);
    
    // Create component
    const component = figma.createComponent();
    component.name = 'Button';
    component.appendChild(button);
    
    figma.currentPage.appendChild(component);
    figma.viewport.scrollAndZoomIntoView([component]);
    
    figma.notify('Component created!');
  }
  
  if (msg.type === 'generate-styles') {
    // Create color styles
    const colors = [
      { name: 'Primary/500', color: { r: 0.23, g: 0.51, b: 0.96 } },
      { name: 'Primary/600', color: { r: 0.15, g: 0.39, b: 0.92 } },
      { name: 'Neutral/900', color: { r: 0.09, g: 0.09, b: 0.09 } },
      { name: 'Neutral/500', color: { r: 0.45, g: 0.45, b: 0.45 } },
    ];
    
    colors.forEach(c => {
      const style = figma.createPaintStyle();
      style.name = c.name;
      style.paints = [{ type: 'SOLID', color: c.color }];
    });
    
    figma.notify('Styles generated!');
  }
};
"""
        
        return files


def main():
    parser = argparse.ArgumentParser(description="🎨 Figma-Agent — Design System")
    parser.add_argument("request", nargs="?", help="Что создать")
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = FigmaAgent()
    
    if args.request:
        print(f"🎨 {agent.NAME} создаёт: {args.request}")
        files = agent.process_request(args.request)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"🎨 {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
