#!/usr/bin/env python3
"""
🔗 GraphQL-Agent
GraphQL Specialist агент

Создаёт:
- GraphQL схемы
- Resolvers
- Apollo клиенты
- GraphQL API
"""

import argparse
from pathlib import Path
from typing import Dict


class GraphQLAgent:
    """
    🔗 GraphQL-Agent
    
    Специализация: GraphQL API Development
    Стек: Apollo, GraphQL, TypeScript
    """
    
    NAME = "🔗 GraphQL-Agent"
    ROLE = "GraphQL Specialist"
    EXPERTISE = ["GraphQL", "Apollo", "Resolvers", "Schema Design", "Subscriptions"]
    
    def process_request(self, request: str) -> Dict[str, str]:
        files = {}
        
        files["schema.graphql"] = """# GraphQL Schema
# Generated by GraphQL-Agent

type Query {
  # User queries
  me: User
  user(id: ID!): User
  users(limit: Int = 20, offset: Int = 0): [User!]!
  
  # Post queries
  post(id: ID!): Post
  posts(filter: PostFilter, limit: Int = 20, offset: Int = 0): [Post!]!
  postsCount(filter: PostFilter): Int!
}

type Mutation {
  # Auth mutations
  signup(input: SignupInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  logout: Boolean!
  
  # User mutations
  updateUser(id: ID!, input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!
  
  # Post mutations
  createPost(input: CreatePostInput!): Post!
  updatePost(id: ID!, input: UpdatePostInput!): Post!
  deletePost(id: ID!): Boolean!
  
  # Like/Comment mutations
  likePost(postId: ID!): Like!
  unlikePost(postId: ID!): Boolean!
  createComment(postId: ID!, content: String!): Comment!
}

type Subscription {
  postCreated: Post!
  postUpdated(id: ID!): Post!
  commentAdded(postId: ID!): Comment!
  userOnline: User!
}

type User {
  id: ID!
  email: String!
  username: String!
  displayName: String
  avatar: String
  bio: String
  role: UserRole!
  isOnline: Boolean!
  createdAt: String!
  updatedAt: String!
  posts: [Post!]!
  comments: [Comment!]!
  likes: [Like!]!
  followersCount: Int!
  followingCount: Int!
}

type Post {
  id: ID!
  title: String!
  content: String!
  author: User!
  published: Boolean!
  views: Int!
  likes: [Like!]!
  comments: [Comment!]!
  tags: [String!]!
  createdAt: String!
  updatedAt: String!
}

type Comment {
  id: ID!
  content: String!
  author: User!
  post: Post!
  createdAt: String!
  updatedAt: String!
}

type Like {
  id: ID!
  user: User!
  post: Post!
  createdAt: String!
}

type AuthPayload {
  token: String!
  user: User!
}

enum UserRole {
  USER
  MODERATOR
  ADMIN
}

input PostFilter {
  published: Boolean
  authorId: ID
  tags: [String!]
  search: String
}

input SignupInput {
  email: String!
  username: String!
  password: String!
  displayName: String
}

input LoginInput {
  email: String!
  password: String!
}

input UpdateUserInput {
  displayName: String
  bio: String
  avatar: String
}

input CreatePostInput {
  title: String!
  content: String!
  published: Boolean = true
  tags: [String!]
}

input UpdatePostInput {
  title: String
  content: String
  published: Boolean
  tags: [String!]
}
"""
        
        files["resolvers.ts"] = """import { PubSub } from 'graphql-subscriptions';

const pubsub = new PubSub();

// Mock database
const users = [];
const posts = [];
const comments = [];
const likes = [];

export const resolvers = {
  Query: {
    me: (_, __, { user }) => {
      if (!user) throw new Error('Not authenticated');
      return users.find(u => u.id === user.id);
    },
    
    user: (_, { id }) => {
      return users.find(u => u.id === id);
    },
    
    users: (_, { limit = 20, offset = 0 }) => {
      return users.slice(offset, offset + limit);
    },
    
    post: (_, { id }) => {
      return posts.find(p => p.id === id);
    },
    
    posts: (_, { filter, limit = 20, offset = 0 }) => {
      let result = posts;
      
      if (filter?.published !== undefined) {
        result = result.filter(p => p.published === filter.published);
      }
      
      if (filter?.authorId) {
        result = result.filter(p => p.authorId === filter.authorId);
      }
      
      return result.slice(offset, offset + limit);
    },
    
    postsCount: (_, { filter }) => {
      let result = posts;
      
      if (filter?.published !== undefined) {
        result = result.filter(p => p.published === filter.published);
      }
      
      return result.length;
    },
  },
  
  Mutation: {
    signup: async (_, { input }) => {
      const user = {
        id: String(users.length + 1),
        ...input,
        role: 'USER',
        createdAt: new Date().toISOString(),
      };
      users.push(user);
      
      return {
        token: 'jwt-token-here',
        user,
      };
    },
    
    login: async (_, { input }) => {
      const user = users.find(u => u.email === input.email);
      if (!user) throw new Error('User not found');
      
      return {
        token: 'jwt-token-here',
        user,
      };
    },
    
    createPost: async (_, { input }, { user }) => {
      if (!user) throw new Error('Not authenticated');
      
      const post = {
        id: String(posts.length + 1),
        ...input,
        authorId: user.id,
        views: 0,
        createdAt: new Date().toISOString(),
      };
      posts.push(post);
      
      // Publish subscription event
      pubsub.publish('POST_CREATED', { postCreated: post });
      
      return post;
    },
  },
  
  Subscription: {
    postCreated: {
      subscribe: () => pubsub.asyncIterator(['POST_CREATED']),
    },
  },
  
  User: {
    posts: (parent) => posts.filter(p => p.authorId === parent.id),
    comments: (parent) => comments.filter(c => c.authorId === parent.id),
    likes: (parent) => likes.filter(l => l.userId === parent.id),
    followersCount: () => 0,
    followingCount: () => 0,
  },
  
  Post: {
    author: (parent) => users.find(u => u.id === parent.authorId),
    comments: (parent) => comments.filter(c => c.postId === parent.id),
    likes: (parent) => likes.filter(l => l.postId === parent.id),
  },
  
  Comment: {
    author: (parent) => users.find(u => u.id === parent.authorId),
    post: (parent) => posts.find(p => p.id === parent.postId),
  },
  
  Like: {
    user: (parent) => users.find(u => u.id === parent.userId),
    post: (parent) => posts.find(p => p.id === parent.postId),
  },
};
"""
        
        files["apollo-client.ts"] = """import { ApolloClient, InMemoryCache, createHttpLink, split } from '@apollo/client';
import { GraphQLWsLink } from '@apollo/client/link/subscriptions';
import { createClient } from 'graphql-ws';
import { getMainDefinition } from '@apollo/client/utilities';
import { setContext } from '@apollo/client/link/context';

// HTTP link for queries and mutations
const httpLink = createHttpLink({
  uri: 'http://localhost:4000/graphql',
});

// WebSocket link for subscriptions
const wsLink = new GraphQLWsLink(createClient({
  url: 'ws://localhost:4000/graphql',
}));

// Auth link
const authLink = setContext((_, { headers }) => {
  const token = localStorage.getItem('token');
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  };
});

// Split link based on operation type
const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  authLink.concat(httpLink),
);

export const apolloClient = new ApolloClient({
  link: splitLink,
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
    },
  },
});

// Example queries
export const GET_POSTS = gql`
  query GetPosts($limit: Int, $offset: Int) {
    posts(limit: $limit, offset: $offset) {
      id
      title
      content
      published
      createdAt
      author {
        id
        username
        avatar
      }
      likes {
        id
      }
      comments {
        id
      }
    }
  }
`;

export const CREATE_POST = gql`
  mutation CreatePost($input: CreatePostInput!) {
    createPost(input: $input) {
      id
      title
      content
      createdAt
    }
  }
`;

export const POSTS_SUBSCRIPTION = gql`
  subscription OnPostCreated {
    postCreated {
      id
      title
      content
      author {
        username
      }
    }
  }
`;
"""
        
        return files


def main():
    parser = argparse.ArgumentParser(description="🔗 GraphQL-Agent — GraphQL API")
    parser.add_argument("request", nargs="?", help="Что создать")
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = GraphQLAgent()
    
    if args.request:
        print(f"🔗 {agent.NAME} создаёт: {args.request}")
        files = agent.process_request(args.request)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"🔗 {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
