#!/usr/bin/env python3
"""
🔧 System-Agent
System Utilities агент

Создаёт:
- Системные утилиты
- CLI инструменты
- File watchers
- Process managers
"""

import argparse
from pathlib import Path
from typing import Dict


class SystemAgent:
    """
    🔧 System-Agent
    
    Специализация: Системные утилиты
    Стек: Python, Rust
    """
    
    NAME = "🔧 System-Agent"
    ROLE = "System Developer"
    EXPERTISE = ["System Programming", "CLI", "File System", "Processes", "Python", "Rust"]
    
    def process_request(self, request: str, lang: str = "python") -> Dict[str, str]:
        files = {}
        
        if lang == "rust":
            files = self._generate_rust_utility(request)
        else:
            files = self._generate_python_utility(request)
        
        return files
    
    def _generate_python_utility(self, feature: str) -> Dict[str, str]:
        files = {}
        
        files["system_utility.py"] = f'''#!/usr/bin/env python3
"""
🔧 System Utility
Generated by System-Agent
"""

import os
import sys
import shutil
import subprocess
import argparse
from pathlib import Path
from datetime import datetime
from typing import List, Optional
import json


class SystemUtility:
    """System utility tool"""
    
    def __init__(self):
        self.name = "{feature}"
    
    def disk_usage(self, path: str = "/") -> dict:
        """Get disk usage statistics"""
        usage = shutil.disk_usage(path)
        return {{
            "total": self._format_size(usage.total),
            "used": self._format_size(usage.used),
            "free": self._format_size(usage.free),
            "percent": round(usage.used / usage.total * 100, 2)
        }}
    
    def _format_size(self, size: int) -> str:
        """Format bytes to human readable"""
        for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
            if size < 1024:
                return f"{{size:.2f}} {{unit}}"
            size /= 1024
        return f"{{size:.2f}} PB"
    
    def find_files(self, pattern: str, path: str = ".") -> List[str]:
        """Find files matching pattern"""
        matches = []
        for root, dirs, files in os.walk(path):
            for file in files:
                if pattern in file:
                    matches.append(os.path.join(root, file))
        return matches
    
    def backup(self, source: str, dest: str) -> bool:
        """Create backup of directory"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_name = f"{{Path(source).name}}_{{timestamp}}"
        backup_path = Path(dest) / backup_name
        
        try:
            shutil.copytree(source, backup_path)
            print(f"✅ Backup created: {{backup_path}}")
            return True
        except Exception as e:
            print(f"❌ Backup failed: {{e}}")
            return False
    
    def clean_temp(self, days: int = 7) -> int:
        """Clean temporary files older than N days"""
        temp_dir = Path("/tmp")
        count = 0
        
        for file in temp_dir.iterdir():
            if file.is_file():
                stat = file.stat()
                age_days = (datetime.now().timestamp() - stat.st_mtime) / 86400
                if age_days > days:
                    try:
                        file.unlink()
                        count += 1
                    except:
                        pass
        
        print(f"🗑️ Cleaned {{count}} files")
        return count
    
    def process_list(self) -> List[dict]:
        """List running processes"""
        processes = []
        try:
            result = subprocess.run(['ps', 'aux'], capture_output=True, text=True)
            lines = result.stdout.strip().split('\\n')[1:]  # Skip header
            for line in lines[:10]:  # First 10 processes
                parts = line.split()
                if len(parts) >= 11:
                    processes.append({{
                        'pid': parts[1],
                        'cpu': parts[2],
                        'mem': parts[3],
                        'command': ' '.join(parts[10:])
                    }})
        except:
            pass
        return processes


def main():
    parser = argparse.ArgumentParser(description="🔧 System Utility")
    parser.add_argument("command", choices=["disk", "find", "backup", "clean", "ps"])
    parser.add_argument("--path", default=".", help="Path to operate on")
    parser.add_argument("--pattern", help="File pattern to find")
    parser.add_argument("--source", help="Backup source")
    parser.add_argument("--dest", help="Backup destination")
    parser.add_argument("--days", type=int, default=7, help="Days for cleanup")
    
    args = parser.parse_args()
    
    util = SystemUtility()
    
    if args.command == "disk":
        print(json.dumps(util.disk_usage(args.path), indent=2))
    elif args.command == "find":
        if not args.pattern:
            print("❌ Pattern required")
            return
        files = util.find_files(args.pattern, args.path)
        for f in files:
            print(f)
    elif args.command == "backup":
        if not args.source or not args.dest:
            print("❌ Source and destination required")
            return
        util.backup(args.source, args.dest)
    elif args.command == "clean":
        util.clean_temp(args.days)
    elif args.command == "ps":
        processes = util.process_list()
        for p in processes:
            print(f"{{p['pid']:>8}} {{p['cpu']:>6}}% {{p['mem']:>6}}% {{p['command'][:50]}}")


if __name__ == "__main__":
    main()
'''
        return files
    
    def _generate_rust_utility(self, feature: str) -> Dict[str, str]:
        files = {}
        
        files["Cargo.toml"] = f"""[package]
name = "system-utility"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = {{ version = "4.0", features = ["derive"] }}
chrono = "0.4"
walkdir = "2"
indicatif = "0.17"
"""
        
        files["src/main.rs"] = f"""use clap::{{Parser, Subcommand}};
use std::fs;
use std::path::Path;

#[derive(Parser)]
#[command(name = "sysutil")]
#[command(about = "System utility tool")]
struct Cli {{
    #[command(subcommand)]
    command: Commands,
}}

#[derive(Subcommand)]
enum Commands {{
    /// Show disk usage
    Disk {{}},
    /// Find files
    Find {{
        pattern: String,
    }},
    /// List processes
    Ps {{}},
}}

fn main() {{
    let cli = Cli::parse();
    
    match cli.command {{
        Commands::Disk {{}} => {{
            println!("💾 Disk Usage:");
            // Implementation here
        }}
        Commands::Find {{ pattern }} => {{
            println!("🔍 Finding: {{}}", pattern);
            // Implementation here
        }}
        Commands::Ps {{}} => {{
            println!("⚙️  Processes:");
            // Implementation here
        }}
    }}
}}
"""
        
        return files


def main():
    parser = argparse.ArgumentParser(description="🔧 System-Agent — System Utilities")
    parser.add_argument("request", nargs="?", help="Что разработать")
    parser.add_argument("--lang", "-l", default="python", choices=["python", "rust"])
    parser.add_argument("--output", "-o", help="Папка для сохранения")
    
    args = parser.parse_args()
    
    agent = SystemAgent()
    
    if args.request:
        print(f"🔧 {agent.NAME} создаёт: {args.request}")
        files = agent.process_request(args.request, args.lang)
        
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in files.items():
                filepath = output_dir / filename
                filepath.parent.mkdir(parents=True, exist_ok=True)
                filepath.write_text(content, encoding="utf-8")
                print(f"✅ {filename}")
        else:
            for filename, content in files.items():
                print(f"\n{'='*50}")
                print(f"📄 {filename}")
                print('='*50)
                print(content[:500] + "..." if len(content) > 500 else content)
    else:
        print(f"🔧 {agent.NAME}")
        print(f"Роль: {agent.ROLE}")


if __name__ == "__main__":
    main()
